import "./globals.css";
import Navbar from "./component/Navbar/Navbar";
import Footer from "./component/Footer/Footer";
import LenisProvider from "./Providers/LenisProviders";
import ScrollToTopButton from "./component/ScrollTopButton/ScrollTopButton";
import { Nunito, Merienda, Roboto, Fira_Code } from "next/font/google";
const nunito = Nunito({ subsets: ["latin"], weight: ["200", "400", "700"] });
export const metadata = {
  title: "Portfolio | Arpan Dey",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={nunito.className}>
      <body className={` antialiased  `}>
        <Navbar />
        <LenisProvider>
          {children}
          <ScrollToTopButton />
        </LenisProvider>
        <Footer />
      </body>
    </html>
  );
}
