import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar/Navbar";
import Footer from "./component/Footer/Footer";
import LenisProvider from "./Providers/LenisProviders";
import ScrollToTopButton from "./component/ScrollTopButton/ScrollTopButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio | Arpan Dey",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased background`}
      >
        <Navbar />
        <LenisProvider>
          {children}
          <ScrollToTopButton />
        </LenisProvider>

        <Footer />
      </body>
    </html>
  );
}
